### ISSUE TITLE
What is the state of plunder ?

### ISSUE THREAD

**Issue by yindia** [plunder-app/cluster-api-plunder#20]
Hey, I found it interesting and I am also working on a similar kind of tool. It can be a good alternative of a rancher (using cluster API)

What is the state of that project? 
Did it support the management cluster outside the VPC?
Did anyone use it for production?

**Comment by thebsdbox** [comment]
Hello, 

I'm about to re-write it to cluster-api v1alpha3 I've also modified the plunder tooling to use OS images recently to hugely improve deployments times. 

It's just finding the time to finish it up at the moment.

**Comment by yindia** [comment]
let me know if I can help with the work you started to address this. We also did an upgrade for v1alpha3. 

Did it support the management cluster outside the VPC? Meaning management cluster in different VPC and we are deploying k8s cluster in private VPC kind of use case

**Comment by thebsdbox** [comment]
VPC as in AWS VCP ?

Regardless plunder can deploy anywhere that DHCP can run and TCP connectivity exists between nodes.

**Comment by evalsocket** [comment]
Yeah, I am talking about private datacenters. Where we don't have connectivity for ingress traffic. That means the cluster-API management cluster not able to communicate nodes in the private datacenter. Rancher is using tunnel server for communication. We are also using a tunnel for communication between management cluster and VPC where we are creating a cluster
